services:

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yml:/traefik.yml:ro
      - ./config/traefik/dynamic:/dynamic:ro
      - ./config/traefik/acme:/acme
    network_mode: host
  
  #nginx-proxy-manager:
  #  image: jc21/nginx-proxy-manager:latest
  #  container_name: nginx-proxy-manager
  #  restart: unless-stopped
  #  network_mode: host
  #  volumes:
  #    - ./config/npm:/data
  #    - ./config/letsencrypt:/etc/letsencrypt

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
      - "${PORT}:${PORT}/tcp"
    volumes:
      - ./config/wireguard:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      dns:
        ipv4_address: 172.30.0.4

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config/adguardhome:/opt/adguardhome/conf
      - adguard_work:/opt/adguardhome/work
    networks:
      dns:
        ipv4_address: 172.30.0.3
    dns:
      - 172.30.0.2
      - 1.1.1.1
    depends_on:
      - unbound

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    # ports:
    #   - "5335:53/udp" #testing unbound only
    volumes:
      - ./unbound/forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf
      - unbound_data:/opt/unbound/etc/unbound
    networks:
      dns:
        ipv4_address: 172.30.0.2

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    env_file:
      - .env
    #ports:
    #  - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    dns:
      - 172.30.0.3
      - 1.1.1.1
    networks:
      dns:
        ipv4_address: 172.30.0.6
    depends_on:
      - adguardhome

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host
    env_file:
      - .env
    restart: unless-stopped
  
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - beszel_data:/beszel_data

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      LISTEN: 45876
      HUB_URL: ${BESZEL_HUB_URL}
      KEY: ${BESZEL_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      dns:
        ipv4_address: 172.30.0.5

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    volumes:
      - ./config/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.${WG_HOST}
    networks:
      dns:
        ipv4_address: 172.30.0.7
    dns:
      - 172.30.0.3

  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:latest
    container_name: tinyauth
    restart: unless-stopped
    env_file:
      - .env
    networks:
      dns:
        ipv4_address: 172.30.0.8
    volumes:
      - tinyauth_data:/data

volumes:
  adguard_work:
  unbound_data:
  beszel_data:
  tinyauth_data:
networks:
  dns:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24